<div class="slide">

<div class="soft-detail">
</strong><br>
</strong><br>
<p>经过网友上万次测试，兼容市面上99%的电脑型号，简单绿色，一键完成U盘启动盘制作！</p>
软件版本：<strong>[field:banben /]</strong><br>
软件大小：<strong>[field:softsize /] MB</strong><br>
更新日期：[field:pubdate function=MyDate('Y-m-d',@me)/]<br>

<a target="_blank" href="[field:arcurl /]"><strong>详细介绍>></strong></a></div>


<div class="soft-detail" style="top: 235px; left: 700px; width: 130px; height: 30px;">

<p style="color:#ffffff;">已有<script src="[field:phpurl /]/disdls.php?aid=[field:id /]" language="javascript"></script>次下载</p>
</div>

<div class="soft-btn"><a href="[field:arcurl /]">下载</a></div>