<?php
$z[0]=Array("link"," http://pan.baidu.com/share/link?shareid=4040292844&uk=3439594002 ",0,115);
$z[0][4]['text']="百度网盘下载";
$z[1]=Array("link"," http://www.33lc.com/soft/19205.html ",117,197);
$z[1][4]['text']="绿茶下载";
$z[2]=Array("link"," http://www.xpgod.com/soft/5850.html ",199,285);
$z[2][4]['text']="系统天堂下载";
$z[3]=Array("link"," http://www.onlinedown.net/soft/381327.htm ",287,386);
$z[3][4]['text']="华军下载u盘装系统";

?>