<li>
<div class="down-list-btn">
<a href="[field:arcurl/]">立即下载</a>
</div>
<a href="[field:arcurl/]"><img src="/uploads/1-1209161G921D7.png" border="0" alt="<b>[field:title/]</b>"/></a>
	<h4><a href="[field:arcurl/]"><b><b>[field:title/]</b></b></a></h4>
<p>发布时间：<strong>[field:pubdate function="GetDateTimeMK(@me)" /]</strong>　软件大小：<strong>[field:softsize /] MB
</strong></p>
<span><font color="#009900">软件介绍：</font>[field:description/]<a href="[field:arcurl/]">[详细介绍]</a></span>
</li>