<?php
$z[0]=Array("field","",307,326);
$z[0][4]['name']="title";
$z[1]=Array("global","",327,353);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",394,423);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",463,522);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",540,572);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("include","",644,679);
$z[5][4]['filename']="head.htm";
$z[6]=Array("field","",784,814);
$z[6][4]['name']="typename";
$z[7]=Array("list","\r\n<li>\r\n<div class=\"down-list-btn\">\r\n<a href=\"[field:arcurl/]\">立即下载</a>\r\n</div>\r\n<a href=\"[field:arcurl/]\"><img src=\"/uploads/1-1209161G921D7.png\" border=\"0\" alt=\"<b>[field:title/]</b>\"/></a>\r\n	<h4><a href=\"[field:arcurl/]\"><b><b>[field:title/]</b></b></a></h4>\r\n<p>发布时间：<strong>[field:pubdate function=\"GetDateTimeMK(@me)\" /]</strong>　软件大小：<strong>[field:softsize /] MB\r\n</strong></p>\r\n<span><font color=\"#009900\">软件介绍：</font>[field:description/]<a href=\"[field:arcurl/]\">[详细介绍]</a></span>\r\n</li>\r\n",853,1437);
$z[7][4]['pagesize']="8";
$z[8]=Array("pagelist","",1492,1563);
$z[8][4]['istitem']="index,pre,next,end,option,info";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",1607,1643);
$z[9][4]['filename']="right.htm";
$z[10]=Array("include","",1709,1746);
$z[10][4]['filename']="footer.htm";

?>