<?php
$z[0]=Array("field","",307,326);
$z[0][4]['name']="title";
$z[1]=Array("global","",327,353);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("field","",394,423);
$z[2][4]['name']="keywords";
$z[3]=Array("field","",463,522);
$z[3][4]['name']="description";
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("global","",540,572);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("include","",644,679);
$z[5][4]['filename']="head.htm";
$z[6]=Array("field","",784,814);
$z[6][4]['name']="typename";
$z[7]=Array("list","\r\n<li>\r\n<p>[field:pubdate function=\"GetDateTimeMK(@me)\" /]</p>\r\n<h4><a href=\"[field:arcurl/]\">[field:title/]</a> </h4>\r\n<span>[field:description/]...<a href=\"[field:arcurl/]\">[阅读全文]</a></span>\r\n</li>\r\n",853,1099);
$z[7][4]['pagesize']="8";
$z[8]=Array("pagelist","",1156,1227);
$z[8][4]['istitem']="index,pre,next,end,option,info";
$z[8][4]['listsize']="5";
$z[9]=Array("include","",1273,1309);
$z[9][4]['filename']="right.htm";
$z[10]=Array("include","",1379,1416);
$z[10][4]['filename']="footer.htm";

?>