<?php
$z[0]=Array("arclist","\r\n\r\n<div class=\"newdown\">\r\n<div class=\"newdowntop\">\r\n<img src=\"/uploads/load.jpg\"/>\r\n<div class=\"newdowninfo\"><a href=\"[field:arcurl /]\">下载最新版本</a><br/>版本：[field:banben /]<br/>更新：[field:pubdate function=MyDate('Y-m-d',@me)/]</div>\r\n</div>\r\n<div class=\"newdownfoot\">\r\n<a href=\"[field:arcurl /]\">\r\n\r\n<img src=\"/uploads/down.jpg\" border=\"0\"></a></div>\r\n</div>\r\n          ",27,535);
$z[0][4]['addfields']="banben";
$z[0][4]['channelid']="3";
$z[0][4]['row']="1";
$z[0][4]['typeid']="3";
$z[0][4]['orderby']="pubdate";
$z[0][4]['orderway']="desc";
$z[1]=Array("arclist","\r\n          <li><a href=\"[field:arcurl /]\">[field:title /]</a></li>\r\n          ",643,819);
$z[1][4]['row']="5";
$z[1][4]['typeid']="3";
$z[1][4]['titlelen']="45";
$z[1][4]['orderby']="pubdate";
$z[1][4]['orderway']="desc";
$z[2]=Array("arclist","\r\n          <li><a href=\"[field:arcurl /]\">[field:title /]</a></li>\r\n          ",953,1127);
$z[2][4]['row']="5";
$z[2][4]['typeid']="3";
$z[2][4]['titlelen']="45";
$z[2][4]['orderby']="click";
$z[2][4]['orderway']="desc";
$z[3]=Array("type","[field:typename/]",1213,1264);
$z[3][4]['typeid']="4";
$z[4]=Array("arclist","\r\n          <li><a href=\"[field:arcurl /]\">[field:title /]</a></li>\r\n          ",1308,1470);
$z[4][4]['row']="5";
$z[4][4]['typeid']="4";
$z[4][4]['orderby']="pubdate";
$z[4][4]['orderway']="desc";
$z[5]=Array("global","",1565,1597);
$z[5][4]['name']="cfg_templets_skin";

?>